/**
 * Enumeration of all lecture/course type categories at the university.
 * Used to classify the nature and format of the lecture.
 */
export type LectureType = 'Vorlesung' | 'Uebung' | 'Praktikum' | 'Tutorium' | 'Seminar' | 'Other' | 'Anderes';

/**
 * Lecture interface represents a course/class that occurs at scheduled times.
 * Includes professor information, room assignment, and scheduling details.
 */
export interface Lecture {
    /** Optional unique identifier (generated by database) */
    id?: string;
    /** Name/title of the lecture (e.g., "Introduction to Computer Science") */
    name: string;
    /** Type of lecture (lecture, exercise, practical, etc.) */
    type: LectureType;
    /** Optional subject or course code (e.g., "CS101") */
    subject?: string;
    /** ID or name of the professor teaching this lecture */
    professor: string;
    /** ID of the room where this lecture is held */
    roomId: string;
    /** Day of the week (e.g., "Monday", "Tuesday") */
    day: string;
    /** Start time in HH:MM format (e.g., "14:00") */
    startTime: string;
    /** End time in HH:MM format (e.g., "16:00") */
    endTime: string;
    /** Optional start date for semester-based lectures in ISO format */
    startDate?: string;
    /** Optional end date for semester-based lectures in ISO format */
    endDate?: string;
}