import { useState, useCallback } from 'react';
import { RoomWithStatus, Lecture, Booking } from '@/models';
import { getAllRooms, addRoom as addRoomService, updateRoom as updateRoomService, deleteRoom as deleteRoomService } from "@/services/firebase";
import { checkRoomAvailability } from '@/utils/availability';

/**
 * Custom hook for managing room data and operations.
 * Handles CRUD operations for rooms and computes real-time availability status.
 * 
 * @param classes - Array of all lectures to check room availability
 * @param bookings - Array of all bookings to check room availability
 * @returns Object containing room data and operations
 */
export function useRoomData(classes: Lecture[], bookings: Booking[]) {
  const [rooms, setRooms] = useState<RoomWithStatus[]>([]);

  /**
   * Refreshes the rooms list from Firebase.
   * Called after any room CRUD operation to keep data in sync.
   */
  const refreshRooms = useCallback(async () => {
    const updatedRooms = await getAllRooms();
    setRooms(updatedRooms);
  }, []);

  /**
   * Adds a new room to the database.
   * 
   * @param room - Room data to add (ID will be generated by Firebase)
   */
  const addRoom = async (room: RoomWithStatus) => {
    const { id, ...roomData } = room;
    await addRoomService(roomData);
    await refreshRooms();
  };

  /**
   * Updates an existing room's properties.
   * 
   * @param id - ID of the room to update
   * @param updates - Partial room object with fields to update
   */
  const updateRoom = async (id: string, updates: Partial<RoomWithStatus>) => {
    await updateRoomService(id, updates);
    await refreshRooms();
  };

  /**
   * Deletes a room from the database.
   * 
   * @param id - ID of the room to delete
   */
  const deleteRoom = async (id: string) => {
    await deleteRoomService(id);
    await refreshRooms();
  };

  // Compute availability status for each room based on lectures and bookings
  const roomsWithDerivedStatus = rooms.map(room => ({
    ...room,
    isAvailable: checkRoomAvailability(room.id, classes, bookings)
  }));

  return { rooms: roomsWithDerivedStatus, setRooms, addRoom, updateRoom, deleteRoom, refreshRooms };
}